services:
  - type: web
    name: soporte-tecnico
    env: python
    pythonVersion: 3.11
    buildCommand: bash build.sh
        value: false
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
